services:
  - type: web
    name: telegram-inspection-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:telegram_app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: <твой_токен_бота>
      - key: WEBHOOK_URL
        value: https://telegram-inspection-bot.onrender.com/webhook

